name: Frontend CI
"on":
  workflow_dispatch: null
  pull_request: null
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: "${{ runner.os }}-npm-${{ hashFiles('**/starter/frontend/package-lock.json') }}"
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install dependencies
        run: npm install
      - name: Run linting
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: "${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}"
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
  build:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: "${{ runner.os }}-npm-${{ hashFiles('**/starter/frontend/package-lock.json') }}"
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install dependencies
        run: npm install
      - name: Build application using Docker
        run: >
          docker build --build-arg REACT_APP_MOVIE_API_URL=http://localhost:3000
          --tag=mp-frontend:latest .
